### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by dylmye** [sungmaster/AntiPacMan#6]
Hi, I played this game a lot on my old phone. I can't find the app on my new phone for what I'm assuming is copyright reasons. Do you have an APK of the latest version (1.6.0?)? I finished the game ages ago but I like to replay levels when I'm on the train and don't have signal. Thanks.

**Comment by vmikhav** [comment]
@dylmye nice to know somebody still like this game😊 Game popularity decreased a lot, so I didn't update privacy policy when Google asked for that and game was removed from the market. I saved last build, you can download it [in release section](https://github.com/vmikhav/AntiPacMan/releases/download/v1.6.0/antipacman-1-6-0.apk).
